name: Dwell
options:
  bundleIdPrefix: com.gauntletai
  deploymentTarget:
    iOS: 16.0
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 10.21.0
targets:
  Dwell:
    type: application
    platform: iOS
    sources:
      - path: Sources
        excludes:
          - "Assets.xcassets"
          - "Preview Content"
      - path: Sources/Assets.xcassets
        type: folder
        buildPhase: resources
      - path: Sources/Preview Content
        type: folder
        buildPhase: resources
      - path: Sources/Views/Components
        type: folder
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseFirestoreSwift
      - package: Firebase
        product: FirebaseStorage
    settings:
      base:
        INFOPLIST_FILE: Sources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.gauntletai.dwell
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_ASSET_PATHS: Sources/Preview\ Content
    info:
      path: Sources/Info.plist
      properties:
        CFBundleName: Dwell
        CFBundleDisplayName: Dwell
        CFBundlePackageType: APPL
        CFBundleShortVersionString: 1.0.0
        CFBundleVersion: 1
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
