name: Dwell
options:
  bundleIdPrefix: com.gauntletai
  deploymentTarget:
    iOS: 16.0
    macOS: 13.0
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 10.19.0
targets:
  Core_iOS:
    type: framework
    platform: iOS
    sources:
      - path: Sources/Models
      - path: Sources/Services
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseStorage
      - package: Firebase
        product: FirebaseFirestore
    settings:
      base:
        DEFINES_MODULE: YES
        GENERATE_INFOPLIST_FILE: YES
        SKIP_INSTALL: YES
        OTHER_LDFLAGS: ["-ObjC"]
        PRODUCT_NAME: Core
        PRODUCT_MODULE_NAME: Core
        PRODUCT_BUNDLE_IDENTIFIER: com.gauntletai.Core
        ENABLE_BITCODE: NO
        DYLIB_INSTALL_NAME_BASE: "@rpath"
        DYLIB_COMPATIBILITY_VERSION: 1
        DYLIB_CURRENT_VERSION: 1
        INSTALL_PATH: "@rpath"
        LD_RUNPATH_SEARCH_PATHS: ["$(inherited)", "@executable_path/Frameworks", "@loader_path/Frameworks"]

  Core_macOS:
    type: framework
    platform: macOS
    sources:
      - path: Sources/Models
      - path: Sources/Services
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseStorage
      - package: Firebase
        product: FirebaseFirestore
    settings:
      base:
        DEFINES_MODULE: YES
        GENERATE_INFOPLIST_FILE: YES
        SKIP_INSTALL: YES
        OTHER_LDFLAGS: ["-ObjC"]
        PRODUCT_NAME: Core
        PRODUCT_MODULE_NAME: Core
        PRODUCT_BUNDLE_IDENTIFIER: com.gauntletai.Core
        ENABLE_BITCODE: NO
        DYLIB_INSTALL_NAME_BASE: "@rpath"
        DYLIB_COMPATIBILITY_VERSION: 1
        DYLIB_CURRENT_VERSION: 1
        INSTALL_PATH: "@rpath"
        LD_RUNPATH_SEARCH_PATHS: ["$(inherited)", "@executable_path/../Frameworks", "@loader_path/../Frameworks"]

  ViewModels_iOS:
    type: framework
    platform: iOS
    sources:
      - path: Sources/ViewModels
    dependencies:
      - target: Core_iOS
    settings:
      base:
        DEFINES_MODULE: YES
        GENERATE_INFOPLIST_FILE: YES
        SKIP_INSTALL: YES
        PRODUCT_NAME: ViewModels
        PRODUCT_MODULE_NAME: ViewModels
        PRODUCT_BUNDLE_IDENTIFIER: com.gauntletai.ViewModels
        ENABLE_BITCODE: NO
        DYLIB_INSTALL_NAME_BASE: "@rpath"
        DYLIB_COMPATIBILITY_VERSION: 1
        DYLIB_CURRENT_VERSION: 1
        INSTALL_PATH: "@rpath"
        LD_RUNPATH_SEARCH_PATHS: ["$(inherited)", "@executable_path/Frameworks", "@loader_path/Frameworks"]
        FRAMEWORK_SEARCH_PATHS: ["$(inherited)", "$(BUILT_PRODUCTS_DIR)"]

  ViewModels_macOS:
    type: framework
    platform: macOS
    sources:
      - path: Sources/ViewModels
    dependencies:
      - target: Core_macOS
    settings:
      base:
        DEFINES_MODULE: YES
        GENERATE_INFOPLIST_FILE: YES
        SKIP_INSTALL: YES
        PRODUCT_NAME: ViewModels
        PRODUCT_MODULE_NAME: ViewModels
        PRODUCT_BUNDLE_IDENTIFIER: com.gauntletai.ViewModels
        ENABLE_BITCODE: NO
        DYLIB_INSTALL_NAME_BASE: "@rpath"
        DYLIB_COMPATIBILITY_VERSION: 1
        DYLIB_CURRENT_VERSION: 1
        INSTALL_PATH: "@rpath"
        LD_RUNPATH_SEARCH_PATHS: ["$(inherited)", "@executable_path/../Frameworks", "@loader_path/../Frameworks"]
        FRAMEWORK_SEARCH_PATHS: ["$(inherited)", "$(BUILT_PRODUCTS_DIR)"]

  Views_iOS:
    type: framework
    platform: iOS
    sources:
      - path: Sources/Views
    dependencies:
      - target: Core_iOS
      - target: ViewModels_iOS
    settings:
      base:
        DEFINES_MODULE: YES
        GENERATE_INFOPLIST_FILE: YES
        SKIP_INSTALL: YES
        PRODUCT_NAME: Views
        PRODUCT_MODULE_NAME: Views
        DYLIB_INSTALL_NAME_BASE: "@rpath"
        DYLIB_COMPATIBILITY_VERSION: 1
        DYLIB_CURRENT_VERSION: 1
        INSTALL_PATH: "@rpath"
        LD_RUNPATH_SEARCH_PATHS: ["$(inherited)", "@executable_path/Frameworks", "@loader_path/Frameworks"]
        OTHER_LDFLAGS: ["-framework", "UIKit"]

  Views_macOS:
    type: framework
    platform: macOS
    sources:
      - path: Sources/Views
    dependencies:
      - target: Core_macOS
      - target: ViewModels_macOS
    settings:
      base:
        DEFINES_MODULE: YES
        GENERATE_INFOPLIST_FILE: YES
        SKIP_INSTALL: YES
        PRODUCT_NAME: Views
        PRODUCT_MODULE_NAME: Views
        DYLIB_INSTALL_NAME_BASE: "@rpath"
        DYLIB_COMPATIBILITY_VERSION: 1
        DYLIB_CURRENT_VERSION: 1
        INSTALL_PATH: "@rpath"
        LD_RUNPATH_SEARCH_PATHS: ["$(inherited)", "@executable_path/../Frameworks", "@loader_path/../Frameworks"]
        OTHER_LDFLAGS: ["-framework", "AppKit"]

  Dwell_iOS:
    type: application
    platform: iOS
    sources:
      - path: Sources
        excludes:
          - "Services/**"
          - "Models/**"
          - "ViewModels/**"
          - "Views/**"
      - path: Assets.xcassets
      - path: Preview Content
      - path: GoogleService-Info.plist
        type: file
        buildPhase: resources
    dependencies:
      - target: Core_iOS
        link: true
        embed: true
      - target: ViewModels_iOS
        link: true
        embed: true
      - target: Views_iOS
        link: true
        embed: true
    settings:
      base:
        INFOPLIST_FILE: Sources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.gauntletai.dwell
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_ASSET_PATHS: Preview\ Content
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
        OTHER_LDFLAGS: ["-ObjC"]
        PRODUCT_NAME: Dwell
        FRAMEWORK_SEARCH_PATHS: ["$(inherited)", "$(PLATFORM_DIR)/Developer/Library/Frameworks"]

  Dwell_macOS:
    type: application
    platform: macOS
    sources:
      - path: Sources
        excludes:
          - "Services/**"
          - "Models/**"
          - "ViewModels/**"
          - "Views/**"
      - path: Assets.xcassets
      - path: Preview Content
      - path: GoogleService-Info.plist
        type: file
        buildPhase: resources
    dependencies:
      - target: Core_macOS
        link: true
        embed: true
      - target: ViewModels_macOS
        link: true
        embed: false
      - target: Views_macOS
        link: true
        embed: false
    settings:
      base:
        INFOPLIST_FILE: Sources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.gauntletai.dwell
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_ASSET_PATHS: Preview\ Content
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        OTHER_LDFLAGS: ["-ObjC"]
        PRODUCT_NAME: Dwell
        FRAMEWORK_SEARCH_PATHS: ["$(inherited)", "$(PLATFORM_DIR)/Developer/Library/Frameworks"]
    info:
      path: Sources/Info.plist
      properties:
        CFBundleName: Dwell
        CFBundleDisplayName: Dwell
        CFBundlePackageType: APPL
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
